[package]
name = "sshfs-rs-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
clap = "4.5.17"
env_logger = "0.11.5"
fuser = "0.14.0"
itertools = "0.13.0"
libc = "0.2.158"
log = "0.4.22"
ssh2 = "0.9.4"
